### ISSUE TITLE
 argument to ‘sizeof’ in ‘memset’ call is the same expression as the destination

### ISSUE THREAD

**Issue by nachtzug69** [dailab/libsml#16]
src/sml_value.c: In function ‘sml_value_init’

sml_value *sml_value_init() {
        sml_value *value = (sml_value *) malloc(sizeof(sml_value));
        memset(value, 0, sizeof(value));
        return value;
}

the memset size argument should be either sizeof(*value) or sizeof(sml_value). sizeof(value) is the size of the pointer itself. Can work, but I guess thats wrong... ;-)

**Comment by nachtzug69** [comment]
furthermore, you should check for NULL before feeding the freshly allocated pointer to memset:

if (value != NULL) memset(value, 0, sizeof(sml_value));

**Comment by hmueller01** [comment]
Thanks for your issue report. As you can see in #14 this repo is dead. Can you please make a pull request with these changes on [volkszaehler/libsml](https://github.com/volkszaehler/libsml).

**Comment by hmueller01** [comment]
BTW: The `memset(value, 0, sizeof(value))` issue is fixed there in the meantime.
