### ISSUE TITLE
unnecessary SML_SKIP_OPTIONAL in sml_list_entry_parse()

### ISSUE THREAD

**Issue by stv0g** [dailab/libsml#2]
In my understanding SML_SKIP_OPTIONAL is not required as its get checked again here:
https://github.com/stv0g/libsml/blob/master/sml/src/sml_time.c#L32

My commit:
https://github.com/stv0g/libsml/commit/4ff38d78564f8fc2ff502c69603ff65270863195

**Comment by juriglx** [comment]
SML_SKIP_OPTIONAL was not required anymore and is removed
